import { PrismaClient } from '@prisma/client';
import TopicCard from './components/TopicCard';

export const dynamic = 'force-dynamic';
const prisma = new PrismaClient();

interface TopicData {
  id: number;
  name: string;
  totalQuestions: number;
  setsStarted: number;
  scorePercent: number;
  questionsAnswered: number;
  completedStages: number;
}

async function getTopics(): Promise<TopicData[]> {
  const topics = await prisma.topic.findMany({
    include: {
      _count: { select: { questions: true } },
      sessions: {
        orderBy: { startedAt: 'desc' },
        take: 1,
        include: { userAnswers: true }
      }
    }
  });

  return topics.map(t => {
    const latestSession = t.sessions[0];

    let questionsAnswered = 0;
    let completedStages = 0;

    if (latestSession && latestSession.userAnswers) {
      questionsAnswered = latestSession.userAnswers.length;

      // Calculate completed stages (10 answers per stage)
      const answerCounts: Record<number, number> = {};
      latestSession.userAnswers.forEach((a) => {
        answerCounts[a.stageNumber] = (answerCounts[a.stageNumber] || 0) + 1;
      });

      Object.values(answerCounts).forEach(count => {
        if (count >= 10) completedStages++;
      });
    }

    return {
      id: t.id,
      name: t.name,
      totalQuestions: t._count.questions,
      setsStarted: latestSession?.setsStarted || 0,
      scorePercent: latestSession?.scorePercent || 0,
      questionsAnswered,
      completedStages
    };
  });
}

export default async function Home() {
  const topics = await getTopics();

  return (
    <div className="container" style={{ paddingTop: '60px', paddingBottom: '80px' }}>
      <header style={{ marginBottom: '60px', textAlign: 'center' }}>
        <div style={{
          display: 'inline-block',
          padding: '4px 12px',
          borderRadius: '20px',
          background: 'var(--surface)',
          border: '1px solid var(--border)',
          fontSize: '0.85rem',
          fontWeight: 600,
          marginBottom: '24px',
          color: 'var(--text-dim)',
          boxShadow: 'var(--shadow-sm)'
        }}>
          ✨ AI-POWERED INTERVIEW PREP
        </div>
        <h1 style={{ fontSize: '3.5rem', marginBottom: '24px', letterSpacing: '-0.03em', lineHeight: 1.1 }}>
          Master Product Management<br />
          <span style={{ color: 'var(--text-dim)' }}>One mock at a time.</span>
        </h1>
        <p style={{ color: 'var(--text-dim)', maxWidth: '500px', margin: '0 auto', fontSize: '1.1rem', lineHeight: '1.6' }}>
          Realistic scenario-based questions generated by AI to help you ace your PM interviews.
        </p>
      </header>

      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(360px, 1fr))',
        gap: '40px',
        paddingBottom: '100px'
      }}>
        {topics.map(topic => (
          <TopicCard key={topic.id} topic={topic} />
        ))}
      </div>
    </div>
  );
}
